name: Film Bot CI

on:
  push:
    tags:
      - '*'

env:
  SERVICE_NAME: film-bot

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo $DOCKER_LOGIN
#      - name: set env
#        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
#      - name: docker login
#        run: docker login -u=$DOCKER_LOGIN -p=
#      - name: build image
#        run: docker build -t $DOCKER_LOGIN/$SERVICE_NAME:$RELEASE_VERSION .
#      - name: push image
#        run: docker push $DOCKER_LOGIN/$SERVICE_NAME:$RELEASE_VERSION