#name: Film Bot CI
#
#on:
#  push:
#    branches:
#      - master

#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: test
#        run: ls
#      - name: Set env
#        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
#      - name: build image
#        run: docker build -t maksard99/film-bot:$RELEASE_VERSION .
#      - name: push image
#        run: docker push maksard99/film-bot:$RELEASE_VERSION