name: Film Bot CI

#on:
#  push:
#    tags:
#      - '[0-9]+\.[0-9]+\.[0-9]+'

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build image
        uses: echo Hello ci cd!