name: Film Bot CI

on:
  push:
    tags:
      - '*'

env:
  SERVICE_NAME: film-bot

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Docker
    steps:
      - name: set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: docker login
        run: docker login -u=${{ env.DOCKER_LOGIN }} -p=${{ env.DOCKER_PASSWORD }}
      - name: build image
        run: docker build -t ${{ env.DOCKER_LOGIN }}/$SERVICE_NAME:$RELEASE_VERSION .
      - name: push image
        run: docker push ${{ env.DOCKER_LOGIN }}/$SERVICE_NAME:$RELEASE_VERSION