name: Film Bot CI

on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: build image
        run: docker build -t maksard99/film-bot:$RELEASE_VERSION .
      - name: push image
        run: docker push maksard99/film-bot:$RELEASE_VERSION