name: Film Bot CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Set env
        run: echo ${{ github.event.inputs.tag }}
      - name: test
        run: echo $RELEASE_VERSION
#      - name: build image
#        run: docker build -t maksard99/film-bot:$RELEASE_VERSION .
#      - name: push image
#        run: docker push maksard99/film-bot:$RELEASE_VERSION