name: Film Bot CI

on:
  push:
    tags:
      - '*'

env:
  SERVICE_NAME: film-bot

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Docker
    steps:
      - name: check out code
        uses: actions/checkout@v3
      - name: set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: docker login
        run: docker login -u=${{ secrets.DOCKER_LOGIN }} -p=${{ secrets.DOCKER_PASSWORD }}
      - name: build image
        run: docker build -t ${{ secrets.DOCKER_LOGIN }}/$SERVICE_NAME:$RELEASE_VERSION .
      - name: push image
        run: docker push ${{ secrets.DOCKER_LOGIN }}/$SERVICE_NAME:$RELEASE_VERSION
  deploy:
    runs-on: ubuntu-latest
    environment: Server
    needs:
      - build
    steps:
      - name: set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Connect and run script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          env: RELEASE_VERSION,SERVICE_NAME
          script_stop: true
          script: |
            docker stop $SERVICE_NAME
            docker run --env-file=/home/.env-film-bot --name=$SERVICE_NAME -d --rm maksard99/$SERVICE_NAME:$RELEASE_VERSION