name: Film Bot CI

#on:
#  push:
#    tags:
#      - '[0-9]+\.[0-9]+\.[0-9]+'

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#      - name: build image
#        run: docker build -t maksard99/film-bot:<version> .
#      - name: push image
#        run: docker push maksard99/film-bot:<version>
      - name: test
        run: echo $CI
